const URL="https://trmtgocglawidplcagzc.supabase.co",KEY="sb_publishable_NbJQhCF0GKDljAB2cOxhpw_Lva2P51L";const sb=supabase.createClient(URL,KEY);let db=[],selected=null;
const $=id=>document.getElementById(id), norm=s=>String(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,""), esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function catalog(){if(typeof PLANT_DATABASE!=="undefined")return PLANT_DATABASE;if(typeof plantDatabase!=="undefined")return plantDatabase;if(typeof plantsDatabase!=="undefined")return plantsDatabase;return[]}
function toggle(id,on){$(id).classList.toggle("hidden",!on)}
async function init(){db=catalog();const {data:{session}}=await sb.auth.getSession();if(session){toggle("app",true);load()}else toggle("login",true)}
$("search").oninput=()=>{let q=norm($("search").value);if(!q){$("results").innerHTML="";return}let m=db.filter(p=>norm(p.name).includes(q)||norm(p.botanical).includes(q)).slice(0,12);$("results").innerHTML=m.length?m.map((p,i)=>`<div class="result" data-i="${i}"><b>${esc(p.name)}</b><small>${esc(p.botanical||"")} · ${esc(p.light||"")}</small></div>`).join(""):'<div class="result">Keine passende Pflanze gefunden.</div>';document.querySelectorAll(".result[data-i]").forEach(e=>e.onclick=()=>select(m[+e.dataset.i]))};
function select(p){selected=p;$("search").value=p.name||"";$("name").value=p.name||"";$("light").value=p.light||"";$("watering").value=p.watering||7;$("fertilizing").value=p.fertilizing||30;$("selName").textContent=p.name||"";$("selBotanical").textContent=p.botanical||"";toggle("selected",true);$("results").innerHTML=""}
async function load(){let {data,error}=await sb.from("plants").select("*").order("created_at",{ascending:false});if(error){$("status").textContent=error.message;return}$("count").textContent=data.length;$("plants").innerHTML=data.map(p=>`<article class="plant"><h3>${esc(p.name||"Pflanze")}</h3><div class="species">${esc(p.species||"")}</div><p>Standort: ${esc(p.location||"–")}<br>Licht: ${esc(p.light_level||"–")}<br>Gießen: alle ${p.watering_interval_days||"–"} Tage<br>Düngen: alle ${p.fertilizing_interval_days||"–"} Tage</p></article>`).join("")||"<div>Noch keine Pflanzen.</div>"}
$("loginBtn").onclick=async()=>{let {error}=await sb.auth.signInWithPassword({email:$("email").value.trim(),password:$("password").value});$("authMsg").textContent=error?.message||"";if(!error){toggle("login",false);toggle("app",true);load()}};
$("logoutBtn").onclick=async()=>{await sb.auth.signOut();location.reload()};
$("add").onclick=async()=>{let {data:{user}}=await sb.auth.getUser();if(!user)return $("status").textContent="Bitte zuerst einloggen.";if(!selected)return $("status").textContent="Bitte eine Pflanze aus der Suche auswählen.";let row={user_id:user.id,name:$("name").value.trim()||selected.name,species:selected.botanical||selected.name,location:$("location").value.trim(),light_level:$("light").value,watering_interval_days:+$("watering").value||7,fertilizing_interval_days:+$("fertilizing").value||30,health_status:"Gesund",notes:$("notes").value.trim()};let {data,error}=await sb.from("plants").insert(row).select().single();if(error)return $("status").textContent=error.message;let f=$("photo").files[0];if(f){let path=`${user.id}/${data.id}/${Date.now()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;let u=await sb.storage.from("plant-photos").upload(path,f);if(!u.error)await sb.from("plant_photos").insert({plant_id:data.id,user_id:user.id,photo_path:path,note:"",taken_at:new Date().toISOString()})}$("status").textContent="Pflanze erfolgreich hinzugefügt.";selected=null;["search","name","location","photo","notes"].forEach(id=>$(id).value="");toggle("selected",false);load()};init();